const List<Map<String, dynamic>> rolePermissionsAndRoutes = [
  {
    'role': 'principal',
    'permissions': [
      'dashboard',
      'profile',
      'payslip',
      'all_staff',
      'department_students',
      'announcement',
      'fetched_timetable',
      'timetable',
      'mark_attendance',
      'apply_leave',
      'approve_leave',
      'approve_od_leave',
      'apply_charge_handover',
      'approve_charge_handover',
      'sent_charge_handover',
      'files',
    ],
  },
  {
    'role': 'hod',
    'permissions': [
      'dashboard',
      'profile',
      'payslip',
      'all_staff',
      'department_students',
      'academic_calendar',
      'compose_hod_announcement',
      'student_feedback',
      'fetched_timetable',
      'timetable',
      'mark_attendance',
      'apply_leave',
      'approve_leave',
      'approve_od_leave',
      'apply_charge_handover',
      'approve_charge_handover',
      'sent_charge_handover',
      'files',
    ],
  },
  {
    'role': 'teaching',
    'permissions': [
      'dashboard',
      'profile',
      'payslip',
      'all_staff',
      'department_students',
      'announcement',
      'fetched_timetable',
      'timetable',
      'mark_attendance',
      'apply_leave',
      'apply_od_leave',
      'apply_charge_handover',
      'approve_charge_handover',
      'sent_charge_handover',
      'files',
      'cc_dashboard', // Conditionally added based on CC status
    ],
  },
  {
    'role': 'nonteaching',
    'permissions': [
      'dashboard',
      'profile',
      'payslip',
      'all_staff',
      'department_students',
      'announcement_nonteaching',
      'fetched_timetable',
      'timetable',
      'apply_leave',
      'apply_od_leave',
      'apply_charge_handover',
      'approve_charge_handover',
      'sent_charge_handover',
      'files',
    ],
  },
  {
    'role': 'cc',
    'permissions': [
      'cc_dashboard',
      'profile',
      'payslip',
      'all_staff',
      'department_students',
      'announcement',
      'fetched_timetable',
      'timetable',
      'mark_attendance',
      'apply_leave',
      'apply_od_leave',
      'apply_charge_handover',
      'approve_charge_handover',
      'sent_charge_handover',
      'files',
      'cc_class_students',
    ],
  },
  {
    'role': 'facultymanagement',
    'permissions': [
      'dashboard',
      'add_faculty',
      'view_faculties',
      'department_students',
      'faculty_profile',
      'payslip',
      'apply_leave',
      'payment',
      'academic_calendar',
      'announcement',
    ],
  },
];